### ISSUE TITLE
IoC domain List

### ISSUE THREAD

**Issue by scafroglia93** [StrangerealIntel/CyberThreatIntel#3]
Hi, you have a well prepared list so I wonder if you would like to create a sort of updated domain list to be included in NextDNS.

It could be a fantastic opportunity for open source infosec

https://github.com/nextdns/metadata

**Comment by StrangerealIntel** [comment]
Hi, this possible, is there an API and documentation on the structure for queries? Need to push it on a specific repository for easily parse it? How do you envisage things considering that you have the experience on the protocol to realize like you're developer of the solution.

**Comment by scafroglia93** [comment]
None of that, you should just create a hosts file made up of your IoCs

**Comment by StrangerealIntel** [comment]
Ok, I thought it needed a particular format to automate inclusion on the client, I will push it this in the next analysis.
